# Site settings
title: Ứng dụng đọc truyện online offline tốt nhất Việt Nam.
email: admin@webtruyen.org
description: Ứng dụng đọc truyện online offline tốt nhất Việt Nam. Bao gồm hàng ngàn truyện được tổng hợp và phân loại có chất lượng tốt, được cập nhật thường xuyên, liên tục.

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "webtruyen.github.io" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot:
data-ad-client:
google_ad_client:

google_analytics: "UA-87076648-1"
addthis_id:
disqus_account:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
